"""Add name column to Sessions

Revision ID: 10199c80d211
Revises: 19d802d6fa27
Create Date: 2024-11-09 17:42:14.373315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10199c80d211'
down_revision = '19d802d6fa27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
