"""Change backref for muscle-exercise relationship

Revision ID: 4e440f0cfe4a
Revises: 10199c80d211
Create Date: 2024-11-10 18:25:49.046570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e440f0cfe4a'
down_revision = '10199c80d211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'muscles', ['muscle_id'], ['id'])
        batch_op.drop_column('muscle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('muscle_id')

    # ### end Alembic commands ###
