"""Make muscle_id non-nullable in Exercises

Revision ID: c65f526e2a03
Revises: 4e440f0cfe4a
Create Date: 2024-11-10 18:55:30.948366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65f526e2a03'
down_revision = '4e440f0cfe4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('muscle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('muscle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
